-- ----------------------------
-- Table structure for dtp_resource
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_RESOURCE';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_RESOURCE (
  TABLENAME VARCHAR2(32 CHAR) NOT NULL,
  COLUMNNAME VARCHAR2(32 CHAR) NOT NULL,
  COLUMNVALUE VARCHAR2(32 CHAR) NOT NULL,
  TXID VARCHAR2(32 CHAR) NOT NULL,
  PRIMARY KEY (TABLENAME,COLUMNNAME,COLUMNVALUE)
) TABLESPACE FW_DATA;
