-- ----------------------------
-- Table structure for dtp_trunk
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_TRUNK';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_TRUNK (
  TXID VARCHAR2(32 CHAR) NOT NULL,
  NEEDORDER VARCHAR2(8 CHAR) NOT NULL,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  APPGROUP VARCHAR2(50 CHAR) NOT NULL,
  STARTTIME NUMBER(32,0) DEFAULT '0' NOT NULL,
  PRIMARY KEY (TXID)
) TABLESPACE FW_DATA;

-- ----------------------------
-- Table structure for dtp_branch
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_BRANCH';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_BRANCH (
  BXID VARCHAR2(32 CHAR) NOT NULL,
  PARENTBXID VARCHAR2(32 CHAR),
  TXID VARCHAR2(32 CHAR) NOT NULL,
  INDEXINBRANCH NUMBER(11)  DEFAULT '-1' NOT NULL,
  INDEXINTRUNK NUMBER(11) DEFAULT '-1' NOT NULL,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  APPGROUP VARCHAR2(50 CHAR) NOT NULL,
  PRIMARY KEY (BXID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_BRANCH ADD CONSTRAINT FK_BRANCH_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_branch
-- ----------------------------

-- ----------------------------
-- Table structure for dtp_preparelog
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_PREPARELOG';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_PREPARELOG (
  LOGID VARCHAR2(32 CHAR) NOT NULL,
  BXID VARCHAR2(32 CHAR) NOT NULL,
  TXID VARCHAR2(32 CHAR) NOT NULL,
  LOGINDEX NUMBER(11)  DEFAULT '-1' NOT NULL,
  CONTENT BLOB NOT NULL,
  STATUS VARCHAR2(10 CHAR) NOT NULL,
  PRIMARY KEY (LOGID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_PREPARELOG ADD CONSTRAINT FK_PREPARELOG_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_preparelog
-- ----------------------------

-- ----------------------------
-- Table structure for dtp_submitlog
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_SUBMITLOG';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_SUBMITLOG (
  LOGID varchar2(32 CHAR) NOT NULL,
  BXID varchar2(32 CHAR) NOT NULL,
  TXID varchar2(32 CHAR) NOT NULL,
  LOGINDEX NUMBER(11)  DEFAULT '-1' NOT NULL,
  CONTENT BLOB NOT NULL,
  STATUS VARCHAR2(10 CHAR) NOT NULL ,
  PRIMARY KEY (LOGID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_SUBMITLOG ADD CONSTRAINT FK_SUBMITLOG_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;
ALTER TABLE DTP_SUBMITLOG ADD CONSTRAINT FK_SUBMITLOG_BRANCH_BXID FOREIGN KEY (BXID) REFERENCES DTP_BRANCH (BXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_submitlog
-- ----------------------------

-- ----------------------------
-- Table structure for dtp_resource
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_RESOURCE';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_RESOURCE (
  TABLENAME VARCHAR2(32 CHAR) NOT NULL,
  COLUMNNAME VARCHAR2(32 CHAR) NOT NULL,
  COLUMNVALUE VARCHAR2(32 CHAR) NOT NULL,
  TXID VARCHAR2(32 CHAR) NOT NULL,
  PRIMARY KEY (TABLENAME,COLUMNNAME,COLUMNVALUE)
) TABLESPACE FW_DATA;
