package com.dcits.ensemble.om.cmc.dataTable;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Created by dangyk on 2018/4/23.
 */
public class CmcTranInfoModel implements Serializable{

    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CHANNEL_SEQ_NO
     * @description: 全局流水号
     */
    private String channelSeqNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CHANNEL_SUB_SEQ_NO
     * @description: 子交易序号
     */
    private String channelSubSeqNo;

    private String channelStSubSeqNo;

    private String orderNo;

    private String othClientNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.SERVICE_CODE
     * @description: scp-stria流服务码
     */
    private String serviceCode;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.MESSAGE_TYPE
     * @description: scp-stria流消息码
     */
    private String messageType;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.MESSAGE_CODE
     * @description: scp-stria流消息类型
     */
    private String messageCode;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.TRAN_DATE
     * @description: 下游系统的交易日期
     */
    private String tranDate;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.TRAN_TIMEEX
     * @description: 下游系统的交易时间
     */
    private String tranTimeex;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CHANNEL_TYPE
     * @description: 渠道类型
     */
    private String channelType;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.SUBTRANS_SEQ_NO
     * @description: 交易次序号
     */
    private String subtransSeqNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.TRAN_STATUS
     * @description: 交易流水状态 0:正常 1:撤销成功 2:原交易被撤销 3:冲正成功 4:原交易被冲正 5:未明 6:失败
     */
    private String tranStatus;

    private String revFlag;

    private String cancelFlag;

    private String baseAcctNo;

    private String cdFlag;


    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CARD_NO
     * @description: 卡号
     */
    private String cardNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.OTH_CARD_NO
     * @description: 对手卡号/账号
     */
    private String othCardNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CUSTOMER_ID
     * @description: 客户号
     */
    private String customerId;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CCY
     * @description: 币种
     */
    private String ccy;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.SYSTEM_ID
     * @description: 系统ID
     */
    private String systemId;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.TRAN_TYPE
     * @description: 交易类型对账用
     */
    private String tranType;


    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.TRAN_AMT
     * @description: 交易金额
     */
    private BigDecimal tranAmt;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.ORIG_SEQ_NO
     * @description: 原交易全局流水号
     */
    private String origSeqNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.ORIG_SUB_SEQ_NO
     * @description: 原交易子交易序号
     */
    private String origSubSeqNo;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.BANK_GET_FEE
     * @description: 银行收取手续费
     */
    private Long bankGetFee;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.CUST_SHARE_FEE
     * @description: 持卡人分担手续费
     */
    private Long custShareFee;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.BANK_SHARE_FEE
     * @description: 银行分担手续费
     */
    private Long bankShareFee;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.BANK_PAY_FEE
     * @description: 银行支付给第三方手续费
     */
    private Long bankPayFee;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.ASS_FEE1
     * @description: 第三方支付给银行手续费1(作为转出行)
     */
    private Long assFee1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.ASS_FEE2
     * @description: 第三方支付给银行手续费2(做为转入行)
     */
    private Long assFee2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.SAME_AREA_FLG
     * @description: 跨地区标志 0:境内没有跨区 1:境内跨地区 2:境外
     */
    private String sameAreaFlg;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.EXPAND
     * @description: 扩展字段备份
     */
    private String expand;

    private String settleFlg;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_tran_info.ROUTER_KEY
     * @description: 分库路由关键字
     */
    private String routerKey;

    public BigDecimal getTranAmt() {
        return tranAmt;
    }

    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }

    public String getOthClientNo() {
        return othClientNo;
    }

    public void setOthClientNo(String othClientNo) {
        this.othClientNo = othClientNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CHANNEL_SEQ_NO
     *
     * @return the value of cmc_tran_info.CHANNEL_SEQ_NO
     */
    public String getChannelSeqNo() {
        return channelSeqNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CHANNEL_SEQ_NO
     *
     * @param channelSeqNo the value for cmc_tran_info.CHANNEL_SEQ_NO
     */
    public void setChannelSeqNo(String channelSeqNo) {
        this.channelSeqNo = channelSeqNo == null ? null : channelSeqNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CHANNEL_SUB_SEQ_NO
     *
     * @return the value of cmc_tran_info.CHANNEL_SUB_SEQ_NO
     */
    public String getChannelSubSeqNo() {
        return channelSubSeqNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CHANNEL_SUB_SEQ_NO
     *
     * @param channelSubSeqNo the value for cmc_tran_info.CHANNEL_SUB_SEQ_NO
     */
    public void setChannelSubSeqNo(String channelSubSeqNo) {
        this.channelSubSeqNo = channelSubSeqNo == null ? null : channelSubSeqNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.SERVICE_CODE
     *
     * @return the value of cmc_tran_info.SERVICE_CODE
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.SERVICE_CODE
     *
     * @param serviceCode the value for cmc_tran_info.SERVICE_CODE
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.MESSAGE_TYPE
     *
     * @return the value of cmc_tran_info.MESSAGE_TYPE
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.MESSAGE_TYPE
     *
     * @param messageType the value for cmc_tran_info.MESSAGE_TYPE
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.MESSAGE_CODE
     *
     * @return the value of cmc_tran_info.MESSAGE_CODE
     */
    public String getMessageCode() {
        return messageCode;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.MESSAGE_CODE
     *
     * @param messageCode the value for cmc_tran_info.MESSAGE_CODE
     */
    public void setMessageCode(String messageCode) {
        this.messageCode = messageCode == null ? null : messageCode.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.TRAN_DATE
     *
     * @return the value of cmc_tran_info.TRAN_DATE
     */
    public String getTranDate() {
        return tranDate;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.TRAN_DATE
     *
     * @param tranDate the value for cmc_tran_info.TRAN_DATE
     */
    public void setTranDate(String tranDate) {
        this.tranDate = tranDate == null ? null : tranDate.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.TRAN_TIMEEX
     *
     * @return the value of cmc_tran_info.TRAN_TIMEEX
     */
    public String getTranTimeex() {
        return tranTimeex;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.TRAN_TIMEEX
     *
     * @param tranTimeex the value for cmc_tran_info.TRAN_TIMEEX
     */
    public void setTranTimeex(String tranTimeex) {
        this.tranTimeex = tranTimeex == null ? null : tranTimeex.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CHANNEL_TYPE
     *
     * @return the value of cmc_tran_info.CHANNEL_TYPE
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CHANNEL_TYPE
     *
     * @param channelType the value for cmc_tran_info.CHANNEL_TYPE
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType == null ? null : channelType.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.SUBTRANS_SEQ_NO
     *
     * @return the value of cmc_tran_info.SUBTRANS_SEQ_NO
     */
    public String getSubtransSeqNo() {
        return subtransSeqNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.SUBTRANS_SEQ_NO
     *
     * @param subtransSeqNo the value for cmc_tran_info.SUBTRANS_SEQ_NO
     */
    public void setSubtransSeqNo(String subtransSeqNo) {
        this.subtransSeqNo = subtransSeqNo == null ? null : subtransSeqNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.TRAN_STATUS
     *
     * @return the value of cmc_tran_info.TRAN_STATUS
     */
    public String getTranStatus() {
        return tranStatus;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.TRAN_STATUS
     *
     * @param tranStatus the value for cmc_tran_info.TRAN_STATUS
     */
    public void setTranStatus(String tranStatus) {
        this.tranStatus = tranStatus == null ? null : tranStatus.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CARD_NO
     *
     * @return the value of cmc_tran_info.CARD_NO
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CARD_NO
     *
     * @param cardNo the value for cmc_tran_info.CARD_NO
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.OTH_CARD_NO
     *
     * @return the value of cmc_tran_info.OTH_CARD_NO
     */
    public String getOthCardNo() {
        return othCardNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.OTH_CARD_NO
     *
     * @param othCardNo the value for cmc_tran_info.OTH_CARD_NO
     */
    public void setOthCardNo(String othCardNo) {
        this.othCardNo = othCardNo == null ? null : othCardNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CUSTOMER_ID
     *
     * @return the value of cmc_tran_info.CUSTOMER_ID
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CUSTOMER_ID
     *
     * @param customerId the value for cmc_tran_info.CUSTOMER_ID
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CCY
     *
     * @return the value of cmc_tran_info.CCY
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CCY
     *
     * @param ccy the value for cmc_tran_info.CCY
     */
    public void setCcy(String ccy) {
        this.ccy = ccy == null ? null : ccy.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.SYSTEM_ID
     *
     * @return the value of cmc_tran_info.SYSTEM_ID
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.SYSTEM_ID
     *
     * @param systemId the value for cmc_tran_info.SYSTEM_ID
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.TRAN_TYPE
     *
     * @return the value of cmc_tran_info.TRAN_TYPE
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.TRAN_TYPE
     *
     * @param tranType the value for cmc_tran_info.TRAN_TYPE
     */
    public void setTranType(String tranType) {
        this.tranType = tranType == null ? null : tranType.trim();
    }


    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.ORIG_SEQ_NO
     *
     * @return the value of cmc_tran_info.ORIG_SEQ_NO
     */
    public String getOrigSeqNo() {
        return origSeqNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.ORIG_SEQ_NO
     *
     * @param origSeqNo the value for cmc_tran_info.ORIG_SEQ_NO
     */
    public void setOrigSeqNo(String origSeqNo) {
        this.origSeqNo = origSeqNo == null ? null : origSeqNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.ORIG_SUB_SEQ_NO
     *
     * @return the value of cmc_tran_info.ORIG_SUB_SEQ_NO
     */
    public String getOrigSubSeqNo() {
        return origSubSeqNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.ORIG_SUB_SEQ_NO
     *
     * @param origSubSeqNo the value for cmc_tran_info.ORIG_SUB_SEQ_NO
     */
    public void setOrigSubSeqNo(String origSubSeqNo) {
        this.origSubSeqNo = origSubSeqNo == null ? null : origSubSeqNo.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.BANK_GET_FEE
     *
     * @return the value of cmc_tran_info.BANK_GET_FEE
     */
    public Long getBankGetFee() {
        return bankGetFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.BANK_GET_FEE
     *
     * @param bankGetFee the value for cmc_tran_info.BANK_GET_FEE
     */
    public void setBankGetFee(Long bankGetFee) {
        this.bankGetFee = bankGetFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.CUST_SHARE_FEE
     *
     * @return the value of cmc_tran_info.CUST_SHARE_FEE
     */
    public Long getCustShareFee() {
        return custShareFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.CUST_SHARE_FEE
     *
     * @param custShareFee the value for cmc_tran_info.CUST_SHARE_FEE
     */
    public void setCustShareFee(Long custShareFee) {
        this.custShareFee = custShareFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.BANK_SHARE_FEE
     *
     * @return the value of cmc_tran_info.BANK_SHARE_FEE
     */
    public Long getBankShareFee() {
        return bankShareFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.BANK_SHARE_FEE
     *
     * @param bankShareFee the value for cmc_tran_info.BANK_SHARE_FEE
     */
    public void setBankShareFee(Long bankShareFee) {
        this.bankShareFee = bankShareFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.BANK_PAY_FEE
     *
     * @return the value of cmc_tran_info.BANK_PAY_FEE
     */
    public Long getBankPayFee() {
        return bankPayFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.BANK_PAY_FEE
     *
     * @param bankPayFee the value for cmc_tran_info.BANK_PAY_FEE
     */
    public void setBankPayFee(Long bankPayFee) {
        this.bankPayFee = bankPayFee;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.ASS_FEE1
     *
     * @return the value of cmc_tran_info.ASS_FEE1
     */
    public Long getAssFee1() {
        return assFee1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.ASS_FEE1
     *
     * @param assFee1 the value for cmc_tran_info.ASS_FEE1
     */
    public void setAssFee1(Long assFee1) {
        this.assFee1 = assFee1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.ASS_FEE2
     *
     * @return the value of cmc_tran_info.ASS_FEE2
     */
    public Long getAssFee2() {
        return assFee2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.ASS_FEE2
     *
     * @param assFee2 the value for cmc_tran_info.ASS_FEE2
     */
    public void setAssFee2(Long assFee2) {
        this.assFee2 = assFee2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.SAME_AREA_FLG
     *
     * @return the value of cmc_tran_info.SAME_AREA_FLG
     */
    public String getSameAreaFlg() {
        return sameAreaFlg;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.SAME_AREA_FLG
     *
     * @param sameAreaFlg the value for cmc_tran_info.SAME_AREA_FLG
     */
    public void setSameAreaFlg(String sameAreaFlg) {
        this.sameAreaFlg = sameAreaFlg == null ? null : sameAreaFlg.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.EXPAND
     *
     * @return the value of cmc_tran_info.EXPAND
     */
    public String getExpand() {
        return expand;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.EXPAND
     *
     * @param expand the value for cmc_tran_info.EXPAND
     */
    public void setExpand(String expand) {
        this.expand = expand == null ? null : expand.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_tran_info.ROUTER_KEY
     *
     * @return the value of cmc_tran_info.ROUTER_KEY
     */
    public String getRouterKey() {
        return routerKey;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_tran_info.ROUTER_KEY
     *
     * @param routerKey the value for cmc_tran_info.ROUTER_KEY
     */
    public void setRouterKey(String routerKey) {
        this.routerKey = routerKey == null ? null : routerKey.trim();
    }

    public String getChannelStSubSeqNo() {
        return channelStSubSeqNo;
    }

    public void setChannelStSubSeqNo(String channelStSubSeqNo) {
        this.channelStSubSeqNo = channelStSubSeqNo;
    }
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getRevFlag() {
        return revFlag;
    }

    public void setRevFlag(String revFlag) {
        this.revFlag = revFlag;
    }

    public String getCancelFlag() {
        return cancelFlag;
    }

    public void setCancelFlag(String cancelFlag) {
        this.cancelFlag = cancelFlag;
    }

    public String getBaseAcctNo() {
        return baseAcctNo;
    }

    public void setBaseAcctNo(String baseAcctNo) {
        this.baseAcctNo = baseAcctNo;
    }

    public String getCdFlag() {
        return cdFlag;
    }

    public void setCdFlag(String cdFlag) {
        this.cdFlag = cdFlag;
    }

    public String getSettleFlg() {
        return settleFlg;
    }

    public void setSettleFlg(String settleFlg) {
        this.settleFlg = settleFlg;
    }

}
