/* Formatted on 2016/2/16 15:18:47 (QP5 v5.115.810.9015) */
BEGIN
   EXECUTE IMMEDIATE 'drop table FW_REVERSAL_TRAN';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE FW_REVERSAL_TRAN
(
   REVERSAL_ID        VARCHAR2 (50 CHAR),
   REVERSAL_ARGS      BLOB,
   TRAN_DATE          VARCHAR2 (20 CHAR),
   REVERSAL_DATE      VARCHAR2 (20 CHAR),
   MAX_REVERSAL_CNT   NUMBER,
   REVERSAL_CNT       NUMBER,
   REVERSAL_BEAN_ID   VARCHAR2 (20 CHAR),
   RET_CODE           VARCHAR2 (20 CHAR),
   RET_MSG            VARCHAR2 (100 CHAR),
   STATUS             VARCHAR2 (1)
) TABLESPACE FW_DATA;



CREATE UNIQUE INDEX FW_REVERSAL_TRAN_PK
   ON FW_REVERSAL_TRAN (REVERSAL_ID) TABLESPACE FW_INDEX;
