BEGIN
   EXECUTE IMMEDIATE 'drop table FW_SEQUENCES';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE FW_SEQUENCES
(
   SEQ_NAME            VARCHAR2 (50 CHAR) NOT NULL,
   SEQ_CURRENT_VALUE   NUMBER NOT NULL,
   SEQ_MAX_VALUE       NUMBER DEFAULT 9999999999 NOT NULL,
   SEQ_MIN_VALUE       NUMBER DEFAULT 1 NOT NULL,
   SEQ_INCREMENT_BY    NUMBER DEFAULT 1 NOT NULL,
   SEQ_CYCLE           VARCHAR2 (1 CHAR) DEFAULT 'Y' NOT NULL,
   SEQ_CACHE           NUMBER DEFAULT 200 NOT NULL
) TABLESPACE FW_DATA;


COMMENT ON COLUMN FW_SEQUENCES.SEQ_NAME IS '序列名称';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CURRENT_VALUE IS '序列值';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_MAX_VALUE IS '最大序列值';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_MIN_VALUE IS '最小序列值';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_INCREMENT_BY IS '序列步长';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CYCLE IS '是否周期序列';

COMMENT ON COLUMN FW_SEQUENCES.SEQ_CACHE IS '缓存系列数';





CREATE UNIQUE INDEX FW_SEQUENCES_PK
   ON FW_SEQUENCES (SEQ_NAME) TABLESPACE FW_INDEX;


ALTER TABLE FW_SEQUENCES ADD (
  CONSTRAINT FW_SEQUENCES_PK
 PRIMARY KEY
 (SEQ_NAME));
