-- ----------------------------
-- Table structure for dtp_trunk
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_TRUNK';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_TRUNK (
  TXID VARCHAR2(32 CHAR) NOT NULL,
  NEEDORDER VARCHAR2(8 CHAR) NOT NULL,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  APPGROUP VARCHAR2(50 CHAR) NOT NULL,
  STARTTIME NUMBER(32,0) DEFAULT '0' NOT NULL,
  PRIMARY KEY (TXID)
) TABLESPACE FW_DATA;

-- ----------------------------
-- Table structure for dtp_branch
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_BRANCH';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_BRANCH (
  BXID VARCHAR2(32 CHAR) NOT NULL,
  PARENTBXID VARCHAR2(32 CHAR),
  TXID VARCHAR2(32 CHAR) NOT NULL,
  INDEXINBRANCH NUMBER(11)  DEFAULT '-1' NOT NULL,
  INDEXINTRUNK NUMBER(11) DEFAULT '-1' NOT NULL,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  APPGROUP VARCHAR2(50 CHAR) NOT NULL,
  PRIMARY KEY (BXID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_BRANCH ADD CONSTRAINT FK_BRANCH_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_branch
-- ----------------------------

-- ----------------------------
-- Table structure for dtp_preparelog
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_PREPARELOG';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_PREPARELOG (
  LOGID VARCHAR2(32 CHAR) NOT NULL,
  BXID VARCHAR2(32 CHAR) NOT NULL,
  TXID VARCHAR2(32 CHAR) NOT NULL,
  LOGINDEX NUMBER(11)  DEFAULT '-1' NOT NULL,
  CONTENT BLOB NOT NULL,
  STATUS VARCHAR2(10 CHAR) NOT NULL,
  PRIMARY KEY (LOGID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_PREPARELOG ADD CONSTRAINT FK_PREPARELOG_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_preparelog
-- ----------------------------

-- ----------------------------
-- Table structure for dtp_submitlog
-- ----------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DTP_SUBMITLOG';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE DTP_SUBMITLOG (
  LOGID varchar2(32 CHAR) NOT NULL,
  BXID varchar2(32 CHAR) NOT NULL,
  TXID varchar2(32 CHAR) NOT NULL,
  LOGINDEX NUMBER(11)  DEFAULT '-1' NOT NULL,
  CONTENT BLOB NOT NULL,
  STATUS VARCHAR2(10 CHAR) NOT NULL ,
  PRIMARY KEY (LOGID)
) TABLESPACE FW_DATA;
ALTER TABLE DTP_SUBMITLOG ADD CONSTRAINT FK_SUBMITLOG_TRUNK_TXID FOREIGN KEY (TXID) REFERENCES DTP_TRUNK (TXID) ON DELETE CASCADE;
ALTER TABLE DTP_SUBMITLOG ADD CONSTRAINT FK_SUBMITLOG_BRANCH_BXID FOREIGN KEY (BXID) REFERENCES DTP_BRANCH (BXID) ON DELETE CASCADE;

-- ----------------------------
-- Records of dtp_submitlog
-- ----------------------------

BEGIN
   EXECUTE IMMEDIATE 'drop table fw_tran_info';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE fw_tran_info (
   SERVICE_ID VARCHAR2(100 char) DEFAULT NULL,
   KEY_VALUE VARCHAR2(200 char) DEFAULT NULL,
   TRAN_DATE VARCHAR2(20 char) DEFAULT NULL,
   TRAN_TIME VARCHAR2(30 char) DEFAULT NULL,
   IN_MSG CLOB,
   OUT_MSG CLOB,
   END_TIME VARCHAR2(30 char) DEFAULT NULL,
   BEAN_RESULT blob,
   SOURCE_TYPE  VARCHAR2(2 char),
   SEQ_NO      VARCHAR2(50 char),
   PROGRAM_ID   VARCHAR2(10 char),
   STATUS       VARCHAR2(1 char),
   REFERENCE    VARCHAR2(50 char),
   PLATFORM_ID  VARCHAR2(32 char),
   USER_ID  VARCHAR2(30 char),
   IP_ADDRESS  VARCHAR2(30 char),
   BRANCH_ID  VARCHAR2(20 char),
   REVERSAL_KEY_VALUE VARCHAR2(200 char),
   WEEK_DAY     number(1)
) TABLESPACE FW_DATA;
/

CREATE UNIQUE INDEX fw_tran_info_pk
   ON fw_tran_info (KEY_VALUE)
   TABLESPACE FW_INDEX NOLOGGING;
/
CREATE INDEX fw_tran_info_idx1
   ON fw_tran_info (TRAN_DATE)
   TABLESPACE FW_INDEX NOLOGGING;
/
CREATE INDEX fw_tran_info_idx2
   ON fw_tran_info (TRAN_TIME,END_TIME)
   TABLESPACE FW_INDEX NOLOGGING;
/
CREATE INDEX fw_tran_info_idx3
   ON fw_tran_info (USER_ID)
   TABLESPACE FW_INDEX NOLOGGING;
/
CREATE INDEX fw_tran_info_idx4
   ON fw_tran_info (BRANCH_ID)
   TABLESPACE FW_INDEX NOLOGGING;
/
CREATE INDEX fw_tran_info_idx5
   ON fw_tran_info (IP_ADDRESS)
   TABLESPACE FW_INDEX NOLOGGING;
/
