DROP TABLE IF EXISTS fw_flow_log;
CREATE TABLE fw_flow_log
(
  FLOW_ID VARCHAR(30) NOT NULL,
  KEY_VALUE VARCHAR(30) NOT NULL,
  BEGIN_TIME BIGINT,
  END_TIME BIGINT,
  STATUS VARCHAR(1),
  REVERSAL_STATUS VARCHAR(1),
  REVERSAL_COUNT INT,
  IN_MSG TEXT,
  OUT_MSG TEXT,
  AFTER_STATUS VARCHAR(1),
  APP_ID VARCHAR(50),
  MQ_ID VARCHAR(50),
  PRIMARY KEY (FLOW_ID, KEY_VALUE)
);

DROP TABLE IF EXISTS fw_flow_node_log;
CREATE TABLE fw_flow_node_log
(
  FLOW_ID VARCHAR(30) NOT NULL,
  KEY_VALUE VARCHAR(100) NOT NULL,
  NODE_ID VARCHAR(30) NOT NULL,
  SEQ_NO INT NOT NULL,
  BEGIN_TIME BIGINT,
  END_TIME BIGINT,
  STATUS VARCHAR(1),
  REVERSAL_STATUS VARCHAR(1),
  IN_MSG TEXT,
  OUT_MSG TEXT,
  CONFIRM_MSG TEXT,
  REVERSAL_MSG TEXT,
  PRIMARY KEY (FLOW_ID, NODE_ID, KEY_VALUE,SEQ_NO)
);
DROP TABLE IF EXISTS fw_flow_node_reversal_log;
CREATE TABLE fw_flow_node_reversal_log
(
  FLOW_ID VARCHAR(30) NOT NULL,
  KEY_VALUE VARCHAR(100) NOT NULL,
  NODE_ID VARCHAR(30) NOT NULL,
  SEQ_NO INT NOT NULL,
  BEGIN_TIME BIGINT,
  END_TIME BIGINT,
  REVERSAL_STATUS VARCHAR(1),
  IN_MSG TEXT,
  OUT_MSG TEXT,
  KEY (FLOW_ID, NODE_ID, KEY_VALUE,SEQ_NO)
);



DROP TABLE IF EXISTS `fw_flow_def`;
CREATE TABLE `fw_flow_def` (
  `FLOW_ID` varchar(20) DEFAULT NULL,
  `FLOW_NAME` varchar(20) DEFAULT NULL,
  `CREATETIME` bigint(20) DEFAULT NULL,
  `CREATOR` varchar(20) DEFAULT NULL,
  `EXEC_TYPE` varchar(1) DEFAULT NULL,
  `RESUME_TYPE` varchar(1) DEFAULT NULL,
  `SCRIPT` varchar(4000) DEFAULT NULL,
  `REVERSAL_TYPE` varchar(1) DEFAULT NULL,
  `TIME_OUT` int(11) DEFAULT NULL,
  `TIMEOUT_DEAL` varchar(1) DEFAULT NULL,
  `LOG_FLAG` varchar(1) DEFAULT NULL,
  `KEY_FIELDS` varchar(200) DEFAULT NULL,
  `INIT_NUM` int(11) DEFAULT NULL,
  UNIQUE KEY `Fw_flow_def_PK` (`FLOW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `fw_flow_node`;
CREATE TABLE `fw_flow_node` (
  `FLOW_ID` varchar(30) NOT NULL DEFAULT '',
  `NODE_ID` varchar(30) NOT NULL DEFAULT '',
  `NODE_DESC` varchar(30) DEFAULT NULL,
  `NODE_TYPE` varchar(1) DEFAULT NULL,
  `NODE_TOP` int(11) DEFAULT NULL,
  `NODE_LEFT` int(11) DEFAULT NULL,
  `NODE_WIDTH` int(11) DEFAULT NULL,
  `NODE_HEIGHT` int(11) DEFAULT NULL,
  `EXEC_TYPE` varchar(1) DEFAULT NULL,
  `SYSTEM_ID` varchar(30) DEFAULT NULL,
  `ERROR_DEAL` varchar(1) DEFAULT NULL,
  `UNKNOW_DEAL` varchar(2) DEFAULT NULL,
  `RETRY_CNT` int(11) DEFAULT NULL,
  `BEFORE_SCRIPT` varchar(1000) DEFAULT NULL,
  `AFTER_SCRIPT` varchar(1000) DEFAULT NULL,
  `MAPPER` varchar(30) DEFAULT NULL,
  `LOOP_IDX` varchar(30) DEFAULT NULL,
  `LOOP_EXPR` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`FLOW_ID`,`NODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `fw_flow_line`;
CREATE TABLE `fw_flow_line` (
  `FLOW_ID` varchar(20) DEFAULT NULL,
  `FROM_NODE` varchar(20) DEFAULT NULL,
  `TO_NODE` varchar(20) DEFAULT NULL,
  `EXPR` varchar(2000) DEFAULT NULL,
  `ID` varchar(20) DEFAULT NULL,
  `TYPE` varchar(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;