--数据同步定义表
BEGIN
   EXECUTE IMMEDIATE 'drop table BATCH_DATA_SYNC_DEF';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;

CREATE TABLE BATCH_DATA_SYNC_DEF
(
  SYNC_ID                 VARCHAR2(30 CHAR)     NOT NULL,
  SYNC_FLAG               VARCHAR2(50 CHAR),
  SHARD_MANAGE_ID         VARCHAR2(30 CHAR),
  TABLE_NAME              VARCHAR2(1000 CHAR),
  WHERE_SQL               VARCHAR2(100 CHAR),
  SELECT_NAMESPACE        VARCHAR2(50 CHAR),
  SELECT_SQL_ID           VARCHAR2(100 CHAR),
  FILE_PATH               VARCHAR2(100 CHAR),
  FILE_NAME               VARCHAR2(100 CHAR),
  FILE_WRITE_TYPE         VARCHAR2(100 CHAR),
  FILE_FORMAT             VARCHAR2(50 CHAR),
  INSERT_SHARD_MANAGE_ID  VARCHAR2(30 CHAR),
  TARGET_TABLE_NAME       VARCHAR2(30 CHAR),
  MATCH_FLAG              VARCHAR2(50 CHAR),
  INSERT_NAMESPACE        VARCHAR2(100 CHAR),
  INSERT_SQL_ID           VARCHAR2(50 CHAR),
  KEY_FIELD               VARCHAR2(30 CHAR)
)
TABLESPACE FW_DATA;
CREATE UNIQUE INDEX SYNC_ID_INDEX ON BATCH_DATA_SYNC_DEF(SYNC_ID); 
