BEGIN
   EXECUTE IMMEDIATE 'alter table FW_FLOW_LOG add (REVERSAL_COUNT NUMBER)';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FW_FLOW_NODE_REVERSAL_LOG';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
CREATE TABLE FW_FLOW_NODE_REVERSAL_LOG
(
  FLOW_ID VARCHAR2(30 CHAR) NOT NULL,
  KEY_VALUE VARCHAR2(100 CHAR) NOT NULL,
  NODE_ID VARCHAR2(30 CHAR) NOT NULL,
  SEQ_NO NUMBER,
  BEGIN_TIME NUMBER,
  END_TIME NUMBER,
  REVERSAL_STATUS VARCHAR2(1 CHAR),
  IN_MSG CLOB,
  OUT_MSG CLOB
);
/
CREATE INDEX fw_flow_node_reversal_log_idx
  ON fw_flow_node_reversal_log (FLOW_ID, NODE_ID, KEY_VALUE,SEQ_NO);
/
  BEGIN
     EXECUTE IMMEDIATE 'alter table batch_timer_def add (IS_SPLIT VARCHAR2(1 CHAR))';
  EXCEPTION
     WHEN OTHERS
     THEN
        NULL;
  END;
  /


  BEGIN
     EXECUTE IMMEDIATE 'alter table batch_run_job add (FAIL_CNT            INTEGER DEFAULT 0 NOT NULL)';
  EXCEPTION
     WHEN OTHERS
     THEN
        NULL;
  END;
  /


  BEGIN
     EXECUTE IMMEDIATE 'alter table batch_run_job add (SPLIT_FAIL_CNT      INTEGER DEFAULT 0 NOT NULL)';
  EXCEPTION
     WHEN OTHERS
     THEN
        NULL;
  END;
  /
