DROP TABLE IF EXISTS fw_sequences;
CREATE TABLE fw_sequences (
  SEQ_NAME varchar(50) NOT NULL COMMENT '序列名称',
  SEQ_CURRENT_VALUE decimal NOT NULL DEFAULT 1 COMMENT '序列值',
  SEQ_MAX_VALUE decimal(32,0) DEFAULT NULL DEFAULT 9999999999 COMMENT '最大序列值',
  SEQ_MIN_VALUE decimal DEFAULT NULL DEFAULT 1 COMMENT '最小序列值',
  SEQ_INCREMENT_BY decimal DEFAULT NULL DEFAULT 1 COMMENT '序列步长',
  SEQ_CYCLE varchar(1) DEFAULT NULL DEFAULT 'Y' COMMENT '是否周期序列',
  SEQ_CACHE decimal DEFAULT NULL DEFAULT 200 COMMENT '缓存系列数',
  PRIMARY KEY (SEQ_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自增序列表';