DROP TABLE IF EXISTS batch_to_commit;
CREATE TABLE batch_to_commit
(
    TASK_ID VARCHAR( 50)  not null,
    SHARD_MANAGER_ID    VARCHAR(50),
    SHARD_ID  VARCHAR(50),
    COMMIT_DATA  BLOB,
    GROUP_ID  VARCHAR(50),
    BATCH_GROUP_ID  VARCHAR(50),
    IDEM_ID  VARCHAR(50),
    RECORD_DATE  VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
