DROP TABLE IF EXISTS batch_timer_def;
CREATE TABLE batch_timer_def
(
  TIMER_ID  VARCHAR (32),
  CRON_EXPRESSION  VARCHAR (32),
  SYSTEM_ID  VARCHAR (32),
  STATIC_PARAM  VARCHAR (100),
  GX_CLASS_NAME  VARCHAR (100),
  GX_METHOD  VARCHAR (100),
  STATUS   VARCHAR (1),
  PAUSE_BATCH VARCHAR (4),
  REC_FLAG  VARCHAR(1),
  IS_SPLIT VARCHAR(1),
  UNIQUE KEY BATCH_TIMER_DEF_PK (TIMER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS batch_timer_rec;
CREATE TABLE batch_timer_rec
(
  TIME_EXE_IND  VARCHAR (100),
  TIMER_ID  VARCHAR (32),
  SYSTEM_ID  VARCHAR (32),
  STATIC_PARAM  VARCHAR (100),
  GX_CLASS_NAME  VARCHAR (100),
  GX_METHOD  VARCHAR (100),
  EXE_RESULT   VARCHAR (1),
  NODE_IP VARCHAR (32),
  START_TIME VARCHAR (32),
  END_TIME VARCHAR (32),
  TIME_ELAPSED INTEGER,
  ERROR_DESC VARCHAR (4000),
  UNIQUE KEY BATCH_TIMER_REC_PK (TIME_EXE_IND)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;