/* 批量参数导出定义表 */
BEGIN
   EXECUTE IMMEDIATE 'drop table BATCH_PARAM_TABLE_DEF';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE BATCH_PARAM_TABLE_DEF
(
   SEQ_NO              VARCHAR2 (32 CHAR),
   TABLE_NAME          VARCHAR2 (30 CHAR),
   TARGET_TABLE_NAME   VARCHAR2 (30 CHAR),
   DATA_SOURCE         VARCHAR2 (20 CHAR),
   SELECT_NAMESPACE    VARCHAR2 (100 CHAR),
   SELECT_SQL_ID       VARCHAR2 (50 CHAR),
   INSERT_NAMESPACE    VARCHAR2 (100 CHAR),
   INSERT_SQL_ID       VARCHAR2 (50 CHAR),
   WHERE_SQL           VARCHAR2 (1000 CHAR),
   BATCH_SIZE          NUMBER
) TABLESPACE FW_DATA;



CREATE UNIQUE INDEX BATCH_PARAM_TABLE_DEF_pk
   ON BATCH_PARAM_TABLE_DEF (SEQ_NO)
   TABLESPACE FW_INDEX NOLOGGING;

