BEGIN
   EXECUTE IMMEDIATE 'drop table BATCH_TIMER_DEF';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
CREATE TABLE BATCH_TIMER_DEF
(
  TIMER_ID  VARCHAR2 (32),
  CRON_EXPRESSION  VARCHAR2 (32),
  SYSTEM_ID  VARCHAR2 (32),
  STATIC_PARAM  VARCHAR2 (100),
  GX_CLASS_NAME  VARCHAR2 (100),
  GX_METHOD  VARCHAR2 (100),
  STATUS   VARCHAR2 (1),
  PAUSE_BATCH VARCHAR2(4),
  REC_FLAG  VARCHAR2(1),
  IS_SPLIT VARCHAR2(1)
);
CREATE UNIQUE INDEX BATCH_TIMER_DEF_pk
   ON BATCH_TIMER_DEF (TIMER_ID);
BEGIN
   EXECUTE IMMEDIATE 'drop table BATCH_TIMER_REC';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
CREATE TABLE BATCH_TIMER_REC
(
  TIME_EXE_IND  VARCHAR2 (100),
  TIMER_ID  VARCHAR2 (32),
  SYSTEM_ID  VARCHAR2 (32),
  STATIC_PARAM  VARCHAR2 (100),
  GX_CLASS_NAME  VARCHAR2 (100),
  GX_METHOD  VARCHAR2 (100),
  EXE_RESULT   VARCHAR2 (1),
  NODE_IP VARCHAR2 (32),
  START_TIME VARCHAR2 (32),
  END_TIME VARCHAR2 (32),
  TIME_ELAPSED NUMBER ,
  ERROR_DESC VARCHAR2 (4000)
);

CREATE UNIQUE INDEX BATCH_TIMER_REC_pk
   ON BATCH_TIMER_REC (TIME_EXE_IND);