package com.dcits.ensemble.om.cmc.dbModel;

import com.dcits.galaxy.base.bean.AbstractBean;
import com.dcits.galaxy.dal.annotation.TablePk;

/**
 * This class corresponds to the database table cmc_card_no_role_info
 * @description 卡号规则信息表
 */
public class CmcCardNoRoleInfo extends AbstractBean {

    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.CARD_NO_ROLE_CODE
     * @description: 规则序号
     */
    @TablePk(index = 1)
    private String cardNoRoleCode;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.LEN_OF_CARD_NO
     * @description: 卡号长度
     */
    private String lenOfCardNo;

    public String getCardGenId() {
        return cardGenId;
    }

    public void setCardGenId(String cardGenId) {
        this.cardGenId = cardGenId == null ? null : cardGenId.trim();
    }

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.CARD_GEN_FUNC
     * @description: 卡号生成规则ID
     */
    private String cardGenId;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.SEQ_NO_LEN
     * @description: 顺序号长度
     */
    private String seqNoLen;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDNUM1
     * @description: 顺序号前域的个数
     */
    private String fldnum1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL1
     * @description: 域1来源表 如空，则为卡片种类表
     */
    private String fldsrctbl1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD1
     * @description: 域1来源域
     */
    private String fldsrcfld1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN1
     * @description: 域1长度
     */
    private String fldlen1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR1
     * @description: 域1条件 如空，则为卡片种类
     */
    private String fldwhr1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN1
     * @description: 域1方式  1：数据库配置；2：常量
     */
    private String fldsign1;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL2
     * @description: 域2来源表 如空，则为卡片种类表
     */
    private String fldsrctbl2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD2
     * @description: 域2来源域
     */
    private String fldsrcfld2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN2
     * @description: 域2长度
     */
    private String fldlen2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR2
     * @description: 域2条件 如空，则为卡片种类
     */
    private String fldwhr2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN2
     * @description: 域2方式  1：数据库配置；2：常量
     */
    private String fldsign2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL3
     * @description: 域3来源表 如空，则为卡片种类表
     */
    private String fldsrctbl3;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD3
     * @description: 域3来源域
     */
    private String fldsrcfld3;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN3
     * @description: 域3长度
     */
    private String fldlen3;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR3
     * @description: 域3条件 如空，则为卡片种类
     */
    private String fldwhr3;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN3
     * @description: 域3方式   1：数据库配置；2：常量
     */
    private String fldsign3;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL4
     * @description: 域4来源表 如空，则为卡片种类表
     */
    private String fldsrctbl4;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD4
     * @description: 域4来源域
     */
    private String fldsrcfld4;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN4
     * @description: 域4长度
     */
    private String fldlen4;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR4
     * @description: 域4条件 如空，则为卡片种类
     */
    private String fldwhr4;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN4
     * @description: 域4方式   1：数据库配置；2：常量
     */
    private String fldsign4;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL5
     * @description: 域5来源表  如空，则为卡片种类表
     */
    private String fldsrctbl5;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD5
     * @description: 域5来源域
     */
    private String fldsrcfld5;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN5
     * @description: 域5长度
     */
    private String fldlen5;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR5
     * @description: 域5条件 如空，则为卡片种类
     */
    private String fldwhr5;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN5
     * @description: 域5方式   1：数据库配置；2：常量
     */
    private String fldsign5;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDNUM2
     * @description: 顺序号后域的个数
     */
    private String fldnum2;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL6
     * @description: 域6来源表  如空，则为卡片种类表
     */
    private String fldsrctbl6;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD6
     * @description: 域6来源域
     */
    private String fldsrcfld6;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN6
     * @description: 域6长度
     */
    private String fldlen6;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR6
     * @description: 域6条件 如空，则为卡片种类
     */
    private String fldwhr6;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN6
     * @description: 域6方式   1：数据库配置；2：常量
     */
    private String fldsign6;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL7
     * @description: 域7来源表 如空，则为卡片种类表
     */
    private String fldsrctbl7;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD7
     * @description: 域7来源域
     */
    private String fldsrcfld7;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN7
     * @description: 域7长度
     */
    private String fldlen7;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR7
     * @description: 域7条件 如空，则为卡片种类
     */
    private String fldwhr7;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN7
     * @description: 域7方式   1：数据库配置；2：常量
     */
    private String fldsign7;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCTBL8
     * @description: 域8来源表  如空，则为卡片种类表
     */
    private String fldsrctbl8;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSRCFLD8
     * @description: 域8来源域
     */
    private String fldsrcfld8;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDLEN8
     * @description: 域8长度
     */
    private String fldlen8;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDWHR8
     * @description: 域8条件 如空，则为卡片种类
     */
    private String fldwhr8;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.FLDSIGN8
     * @description: 域8方式   1：数据库配置；2：常量
     */
    private String fldsign8;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.VRY_BIT_METH
     * @description: 校验位算法 00-luhn算法 01-verhoeff算法
     *   LUHN,//luhn算法
     *  VERHOEFF//verhoeff算法
     */
    private String vryBitMeth;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.VRY_BIT_LEN
     * @description: 校验位长度
     */
    private String vryBitLen;

    /**
     * This field was generated by DAO-Tools Generator.
     * This field corresponds to the database column cmc_card_no_role_info.VRY_GEN_FUNC
     * @description: 校验位生成函数
     */
    private String vryGenFunc;

    private String reqNum;

    private String operateType;

    public String getOperateType() {
        return operateType;
    }

    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    public String getReqNum() {
        return reqNum;
    }

    public void setReqNum(String reqNum) {
        this.reqNum = reqNum;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.CARD_NO_ROLE_CODE
     *
     * @return the value of cmc_card_no_role_info.CARD_NO_ROLE_CODE
     */
    public String getCardNoRoleCode() {
        return cardNoRoleCode;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.CARD_NO_ROLE_CODE
     *
     * @param cardNoRoleCode the value for cmc_card_no_role_info.CARD_NO_ROLE_CODE
     */
    public void setCardNoRoleCode(String cardNoRoleCode) {
        this.cardNoRoleCode = cardNoRoleCode == null ? null : cardNoRoleCode.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.LEN_OF_CARD_NO
     *
     * @return the value of cmc_card_no_role_info.LEN_OF_CARD_NO
     */
    public String getLenOfCardNo() {
        return lenOfCardNo;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.LEN_OF_CARD_NO
     *
     * @param lenOfCardNo the value for cmc_card_no_role_info.LEN_OF_CARD_NO
     */
    public void setLenOfCardNo(String lenOfCardNo) {
        this.lenOfCardNo = lenOfCardNo == null ? null : lenOfCardNo.trim();
    }







    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.SEQ_NO_LEN
     *
     * @return the value of cmc_card_no_role_info.SEQ_NO_LEN
     */
    public String getSeqNoLen() {
        return seqNoLen;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.SEQ_NO_LEN
     *
     * @param seqNoLen the value for cmc_card_no_role_info.SEQ_NO_LEN
     */
    public void setSeqNoLen(String seqNoLen) {
        this.seqNoLen = seqNoLen == null ? null : seqNoLen.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDNUM1
     *
     * @return the value of cmc_card_no_role_info.FLDNUM1
     */
    public String getFldnum1() {
        return fldnum1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDNUM1
     *
     * @param fldnum1 the value for cmc_card_no_role_info.FLDNUM1
     */
    public void setFldnum1(String fldnum1) {
        this.fldnum1 = fldnum1 == null ? null : fldnum1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL1
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL1
     */
    public String getFldsrctbl1() {
        return fldsrctbl1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL1
     *
     * @param fldsrctbl1 the value for cmc_card_no_role_info.FLDSRCTBL1
     */
    public void setFldsrctbl1(String fldsrctbl1) {
        this.fldsrctbl1 = fldsrctbl1 == null ? null : fldsrctbl1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD1
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD1
     */
    public String getFldsrcfld1() {
        return fldsrcfld1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD1
     *
     * @param fldsrcfld1 the value for cmc_card_no_role_info.FLDSRCFLD1
     */
    public void setFldsrcfld1(String fldsrcfld1) {
        this.fldsrcfld1 = fldsrcfld1 == null ? null : fldsrcfld1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN1
     *
     * @return the value of cmc_card_no_role_info.FLDLEN1
     */
    public String getFldlen1() {
        return fldlen1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN1
     *
     * @param fldlen1 the value for cmc_card_no_role_info.FLDLEN1
     */
    public void setFldlen1(String fldlen1) {
        this.fldlen1 = fldlen1 == null ? null : fldlen1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR1
     *
     * @return the value of cmc_card_no_role_info.FLDWHR1
     */
    public String getFldwhr1() {
        return fldwhr1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR1
     *
     * @param fldwhr1 the value for cmc_card_no_role_info.FLDWHR1
     */
    public void setFldwhr1(String fldwhr1) {
        this.fldwhr1 = fldwhr1 == null ? null : fldwhr1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN1
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN1
     */
    public String getFldsign1() {
        return fldsign1;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN1
     *
     * @param fldsign1 the value for cmc_card_no_role_info.FLDSIGN1
     */
    public void setFldsign1(String fldsign1) {
        this.fldsign1 = fldsign1 == null ? null : fldsign1.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL2
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL2
     */
    public String getFldsrctbl2() {
        return fldsrctbl2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL2
     *
     * @param fldsrctbl2 the value for cmc_card_no_role_info.FLDSRCTBL2
     */
    public void setFldsrctbl2(String fldsrctbl2) {
        this.fldsrctbl2 = fldsrctbl2 == null ? null : fldsrctbl2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD2
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD2
     */
    public String getFldsrcfld2() {
        return fldsrcfld2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD2
     *
     * @param fldsrcfld2 the value for cmc_card_no_role_info.FLDSRCFLD2
     */
    public void setFldsrcfld2(String fldsrcfld2) {
        this.fldsrcfld2 = fldsrcfld2 == null ? null : fldsrcfld2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN2
     *
     * @return the value of cmc_card_no_role_info.FLDLEN2
     */
    public String getFldlen2() {
        return fldlen2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN2
     *
     * @param fldlen2 the value for cmc_card_no_role_info.FLDLEN2
     */
    public void setFldlen2(String fldlen2) {
        this.fldlen2 = fldlen2 == null ? null : fldlen2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR2
     *
     * @return the value of cmc_card_no_role_info.FLDWHR2
     */
    public String getFldwhr2() {
        return fldwhr2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR2
     *
     * @param fldwhr2 the value for cmc_card_no_role_info.FLDWHR2
     */
    public void setFldwhr2(String fldwhr2) {
        this.fldwhr2 = fldwhr2 == null ? null : fldwhr2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN2
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN2
     */
    public String getFldsign2() {
        return fldsign2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN2
     *
     * @param fldsign2 the value for cmc_card_no_role_info.FLDSIGN2
     */
    public void setFldsign2(String fldsign2) {
        this.fldsign2 = fldsign2 == null ? null : fldsign2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL3
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL3
     */
    public String getFldsrctbl3() {
        return fldsrctbl3;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL3
     *
     * @param fldsrctbl3 the value for cmc_card_no_role_info.FLDSRCTBL3
     */
    public void setFldsrctbl3(String fldsrctbl3) {
        this.fldsrctbl3 = fldsrctbl3 == null ? null : fldsrctbl3.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD3
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD3
     */
    public String getFldsrcfld3() {
        return fldsrcfld3;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD3
     *
     * @param fldsrcfld3 the value for cmc_card_no_role_info.FLDSRCFLD3
     */
    public void setFldsrcfld3(String fldsrcfld3) {
        this.fldsrcfld3 = fldsrcfld3 == null ? null : fldsrcfld3.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN3
     *
     * @return the value of cmc_card_no_role_info.FLDLEN3
     */
    public String getFldlen3() {
        return fldlen3;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN3
     *
     * @param fldlen3 the value for cmc_card_no_role_info.FLDLEN3
     */
    public void setFldlen3(String fldlen3) {
        this.fldlen3 = fldlen3 == null ? null : fldlen3.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR3
     *
     * @return the value of cmc_card_no_role_info.FLDWHR3
     */
    public String getFldwhr3() {
        return fldwhr3;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR3
     *
     * @param fldwhr3 the value for cmc_card_no_role_info.FLDWHR3
     */
    public void setFldwhr3(String fldwhr3) {
        this.fldwhr3 = fldwhr3 == null ? null : fldwhr3.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN3
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN3
     */
    public String getFldsign3() {
        return fldsign3;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN3
     *
     * @param fldsign3 the value for cmc_card_no_role_info.FLDSIGN3
     */
    public void setFldsign3(String fldsign3) {
        this.fldsign3 = fldsign3 == null ? null : fldsign3.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL4
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL4
     */
    public String getFldsrctbl4() {
        return fldsrctbl4;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL4
     *
     * @param fldsrctbl4 the value for cmc_card_no_role_info.FLDSRCTBL4
     */
    public void setFldsrctbl4(String fldsrctbl4) {
        this.fldsrctbl4 = fldsrctbl4 == null ? null : fldsrctbl4.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD4
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD4
     */
    public String getFldsrcfld4() {
        return fldsrcfld4;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD4
     *
     * @param fldsrcfld4 the value for cmc_card_no_role_info.FLDSRCFLD4
     */
    public void setFldsrcfld4(String fldsrcfld4) {
        this.fldsrcfld4 = fldsrcfld4 == null ? null : fldsrcfld4.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN4
     *
     * @return the value of cmc_card_no_role_info.FLDLEN4
     */
    public String getFldlen4() {
        return fldlen4;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN4
     *
     * @param fldlen4 the value for cmc_card_no_role_info.FLDLEN4
     */
    public void setFldlen4(String fldlen4) {
        this.fldlen4 = fldlen4 == null ? null : fldlen4.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR4
     *
     * @return the value of cmc_card_no_role_info.FLDWHR4
     */
    public String getFldwhr4() {
        return fldwhr4;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR4
     *
     * @param fldwhr4 the value for cmc_card_no_role_info.FLDWHR4
     */
    public void setFldwhr4(String fldwhr4) {
        this.fldwhr4 = fldwhr4 == null ? null : fldwhr4.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN4
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN4
     */
    public String getFldsign4() {
        return fldsign4;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN4
     *
     * @param fldsign4 the value for cmc_card_no_role_info.FLDSIGN4
     */
    public void setFldsign4(String fldsign4) {
        this.fldsign4 = fldsign4 == null ? null : fldsign4.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL5
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL5
     */
    public String getFldsrctbl5() {
        return fldsrctbl5;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL5
     *
     * @param fldsrctbl5 the value for cmc_card_no_role_info.FLDSRCTBL5
     */
    public void setFldsrctbl5(String fldsrctbl5) {
        this.fldsrctbl5 = fldsrctbl5 == null ? null : fldsrctbl5.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD5
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD5
     */
    public String getFldsrcfld5() {
        return fldsrcfld5;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD5
     *
     * @param fldsrcfld5 the value for cmc_card_no_role_info.FLDSRCFLD5
     */
    public void setFldsrcfld5(String fldsrcfld5) {
        this.fldsrcfld5 = fldsrcfld5 == null ? null : fldsrcfld5.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN5
     *
     * @return the value of cmc_card_no_role_info.FLDLEN5
     */
    public String getFldlen5() {
        return fldlen5;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN5
     *
     * @param fldlen5 the value for cmc_card_no_role_info.FLDLEN5
     */
    public void setFldlen5(String fldlen5) {
        this.fldlen5 = fldlen5 == null ? null : fldlen5.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR5
     *
     * @return the value of cmc_card_no_role_info.FLDWHR5
     */
    public String getFldwhr5() {
        return fldwhr5;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR5
     *
     * @param fldwhr5 the value for cmc_card_no_role_info.FLDWHR5
     */
    public void setFldwhr5(String fldwhr5) {
        this.fldwhr5 = fldwhr5 == null ? null : fldwhr5.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN5
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN5
     */
    public String getFldsign5() {
        return fldsign5;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN5
     *
     * @param fldsign5 the value for cmc_card_no_role_info.FLDSIGN5
     */
    public void setFldsign5(String fldsign5) {
        this.fldsign5 = fldsign5 == null ? null : fldsign5.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDNUM2
     *
     * @return the value of cmc_card_no_role_info.FLDNUM2
     */
    public String getFldnum2() {
        return fldnum2;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDNUM2
     *
     * @param fldnum2 the value for cmc_card_no_role_info.FLDNUM2
     */
    public void setFldnum2(String fldnum2) {
        this.fldnum2 = fldnum2 == null ? null : fldnum2.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL6
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL6
     */
    public String getFldsrctbl6() {
        return fldsrctbl6;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL6
     *
     * @param fldsrctbl6 the value for cmc_card_no_role_info.FLDSRCTBL6
     */
    public void setFldsrctbl6(String fldsrctbl6) {
        this.fldsrctbl6 = fldsrctbl6 == null ? null : fldsrctbl6.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD6
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD6
     */
    public String getFldsrcfld6() {
        return fldsrcfld6;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD6
     *
     * @param fldsrcfld6 the value for cmc_card_no_role_info.FLDSRCFLD6
     */
    public void setFldsrcfld6(String fldsrcfld6) {
        this.fldsrcfld6 = fldsrcfld6 == null ? null : fldsrcfld6.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN6
     *
     * @return the value of cmc_card_no_role_info.FLDLEN6
     */
    public String getFldlen6() {
        return fldlen6;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN6
     *
     * @param fldlen6 the value for cmc_card_no_role_info.FLDLEN6
     */
    public void setFldlen6(String fldlen6) {
        this.fldlen6 = fldlen6 == null ? null : fldlen6.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR6
     *
     * @return the value of cmc_card_no_role_info.FLDWHR6
     */
    public String getFldwhr6() {
        return fldwhr6;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR6
     *
     * @param fldwhr6 the value for cmc_card_no_role_info.FLDWHR6
     */
    public void setFldwhr6(String fldwhr6) {
        this.fldwhr6 = fldwhr6 == null ? null : fldwhr6.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN6
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN6
     */
    public String getFldsign6() {
        return fldsign6;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN6
     *
     * @param fldsign6 the value for cmc_card_no_role_info.FLDSIGN6
     */
    public void setFldsign6(String fldsign6) {
        this.fldsign6 = fldsign6 == null ? null : fldsign6.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL7
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL7
     */
    public String getFldsrctbl7() {
        return fldsrctbl7;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL7
     *
     * @param fldsrctbl7 the value for cmc_card_no_role_info.FLDSRCTBL7
     */
    public void setFldsrctbl7(String fldsrctbl7) {
        this.fldsrctbl7 = fldsrctbl7 == null ? null : fldsrctbl7.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD7
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD7
     */
    public String getFldsrcfld7() {
        return fldsrcfld7;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD7
     *
     * @param fldsrcfld7 the value for cmc_card_no_role_info.FLDSRCFLD7
     */
    public void setFldsrcfld7(String fldsrcfld7) {
        this.fldsrcfld7 = fldsrcfld7 == null ? null : fldsrcfld7.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN7
     *
     * @return the value of cmc_card_no_role_info.FLDLEN7
     */
    public String getFldlen7() {
        return fldlen7;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN7
     *
     * @param fldlen7 the value for cmc_card_no_role_info.FLDLEN7
     */
    public void setFldlen7(String fldlen7) {
        this.fldlen7 = fldlen7 == null ? null : fldlen7.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR7
     *
     * @return the value of cmc_card_no_role_info.FLDWHR7
     */
    public String getFldwhr7() {
        return fldwhr7;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR7
     *
     * @param fldwhr7 the value for cmc_card_no_role_info.FLDWHR7
     */
    public void setFldwhr7(String fldwhr7) {
        this.fldwhr7 = fldwhr7 == null ? null : fldwhr7.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN7
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN7
     */
    public String getFldsign7() {
        return fldsign7;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN7
     *
     * @param fldsign7 the value for cmc_card_no_role_info.FLDSIGN7
     */
    public void setFldsign7(String fldsign7) {
        this.fldsign7 = fldsign7 == null ? null : fldsign7.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCTBL8
     *
     * @return the value of cmc_card_no_role_info.FLDSRCTBL8
     */
    public String getFldsrctbl8() {
        return fldsrctbl8;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCTBL8
     *
     * @param fldsrctbl8 the value for cmc_card_no_role_info.FLDSRCTBL8
     */
    public void setFldsrctbl8(String fldsrctbl8) {
        this.fldsrctbl8 = fldsrctbl8 == null ? null : fldsrctbl8.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSRCFLD8
     *
     * @return the value of cmc_card_no_role_info.FLDSRCFLD8
     */
    public String getFldsrcfld8() {
        return fldsrcfld8;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSRCFLD8
     *
     * @param fldsrcfld8 the value for cmc_card_no_role_info.FLDSRCFLD8
     */
    public void setFldsrcfld8(String fldsrcfld8) {
        this.fldsrcfld8 = fldsrcfld8 == null ? null : fldsrcfld8.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDLEN8
     *
     * @return the value of cmc_card_no_role_info.FLDLEN8
     */
    public String getFldlen8() {
        return fldlen8;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDLEN8
     *
     * @param fldlen8 the value for cmc_card_no_role_info.FLDLEN8
     */
    public void setFldlen8(String fldlen8) {
        this.fldlen8 = fldlen8 == null ? null : fldlen8.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDWHR8
     *
     * @return the value of cmc_card_no_role_info.FLDWHR8
     */
    public String getFldwhr8() {
        return fldwhr8;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDWHR8
     *
     * @param fldwhr8 the value for cmc_card_no_role_info.FLDWHR8
     */
    public void setFldwhr8(String fldwhr8) {
        this.fldwhr8 = fldwhr8 == null ? null : fldwhr8.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.FLDSIGN8
     *
     * @return the value of cmc_card_no_role_info.FLDSIGN8
     */
    public String getFldsign8() {
        return fldsign8;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.FLDSIGN8
     *
     * @param fldsign8 the value for cmc_card_no_role_info.FLDSIGN8
     */
    public void setFldsign8(String fldsign8) {
        this.fldsign8 = fldsign8 == null ? null : fldsign8.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.VRY_BIT_METH
     *
     * @return the value of cmc_card_no_role_info.VRY_BIT_METH
     */
    public String getVryBitMeth() {
        return vryBitMeth;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.VRY_BIT_METH
     *
     * @param vryBitMeth the value for cmc_card_no_role_info.VRY_BIT_METH
     */
    public void setVryBitMeth(String vryBitMeth) {
        this.vryBitMeth = vryBitMeth == null ? null : vryBitMeth.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.VRY_BIT_LEN
     *
     * @return the value of cmc_card_no_role_info.VRY_BIT_LEN
     */
    public String getVryBitLen() {
        return vryBitLen;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.VRY_BIT_LEN
     *
     * @param vryBitLen the value for cmc_card_no_role_info.VRY_BIT_LEN
     */
    public void setVryBitLen(String vryBitLen) {
        this.vryBitLen = vryBitLen == null ? null : vryBitLen.trim();
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method returns the value of the database column cmc_card_no_role_info.VRY_GEN_FUNC
     *
     * @return the value of cmc_card_no_role_info.VRY_GEN_FUNC
     */
    public String getVryGenFunc() {
        return vryGenFunc;
    }

    /**
     * This method was generated by DAO-Tools Generator.
     * This method sets the value of the database column cmc_card_no_role_info.VRY_GEN_FUNC
     *
     * @param vryGenFunc the value for cmc_card_no_role_info.VRY_GEN_FUNC
     */
    public void setVryGenFunc(String vryGenFunc) {
        this.vryGenFunc = vryGenFunc == null ? null : vryGenFunc.trim();
    }
}