/* Formatted on 2016/6/1 17:44:24 (QP5 v5.115.810.9015) */
BEGIN
   EXECUTE IMMEDIATE 'alter table BATCH_STD_JOB add(BATCH_SIZE    number)';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'alter table BATCH_RUN_TASK add (ERROR_MSG                 VARCHAR2(500 char))';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'alter table BATCH_RUN_TASK add (TIME_ELAPSED               number)';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'drop table batch_status_hist';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE batch_status_hist
(
   RUN_DATE       VARCHAR2 (8 CHAR),
   BATCH_CLASS    VARCHAR2 (4 CHAR),
   BATCH_STATUS   VARCHAR2 (3 CHAR),
   STOP_BATCH     VARCHAR2 (1 CHAR),
   START_TIME     VARCHAR2 (30 CHAR),
   END_TIME       VARCHAR2 (30 CHAR),
   BATCH_IND      VARCHAR2 (50 CHAR)
) TABLESPACE FW_DATA;

CREATE INDEX batch_status_hist_idx
   ON batch_status_hist (RUN_DATE,BATCH_CLASS)
   TABLESPACE FW_INDEX NOLOGGING;

BEGIN
   EXECUTE IMMEDIATE 'drop table batch_run_task_hist';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE batch_run_task_hist
(
   TASK_ID        VARCHAR2 (50 CHAR) NOT NULL,
   JOB_ID         VARCHAR2 (30 CHAR) NOT NULL,
   TASK_STATUS    VARCHAR2 (1 CHAR) DEFAULT 'N' NOT NULL,
   SEQ_NO         INTEGER,
   START_ROW      NUMBER,
   END_ROW        NUMBER,
   FILE_OFFSET    NUMBER,
   FILE_LIMIT     NUMBER,
   SCHEMA_ID      VARCHAR2 (30 CHAR),
   NODE_IP        VARCHAR2 (30 CHAR),
   ERROR_DESC     VARCHAR2 (4000 CHAR),
   START_TIME     VARCHAR2 (30 CHAR),
   END_TIME       VARCHAR2 (30 CHAR),
   SPLIT_JOB_ID   VARCHAR2 (30 CHAR),
   SYSTEM_ID      VARCHAR2 (30 CHAR),
   APP_ID         VARCHAR2 (50 CHAR),
   RUN_MSG        VARCHAR2 (200 CHAR),
   TASK_IND       VARCHAR2 (50 CHAR),
   START_KEY      VARCHAR (100),
   END_KEY        VARCHAR (100),
   ERROR_MSG      VARCHAR (500 CHAR),
   TIME_ELAPSED   NUMBER,
   RUN_DATE       VARCHAR2 (8 CHAR)
) TABLESPACE FW_DATA;

CREATE INDEX batch_run_task_hist_idx1
   ON batch_run_task_hist (RUN_DATE, JOB_ID)
   TABLESPACE FW_INDEX NOLOGGING;

BEGIN
   EXECUTE IMMEDIATE 'drop table batch_run_job_hist';
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END;
/

CREATE TABLE batch_run_job_hist
(
   JOB_ID       VARCHAR2 (30 CHAR),
   JOB_STATUS   VARCHAR2 (1 CHAR),
   SPLIT_CNT    INTEGER,
   FINISH_CNT   INTEGER,
   START_TIME   VARCHAR2 (30 CHAR),
   END_TIME     VARCHAR2 (30 CHAR),
   PERCENT      VARCHAR2 (30 CHAR),
   RUN_DATE     VARCHAR2 (8 CHAR)
) TABLESPACE FW_DATA;

CREATE INDEX batch_run_job_hist_idx
   ON batch_run_job_hist (RUN_DATE, JOB_ID)
   TABLESPACE FW_INDEX NOLOGGING;
